// <auto-generated />
using System;
using LeontecSyncLogSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeontecSyncLogSystem.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260706060241_InitialMySql")]
    partial class InitialMySql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LeontecSyncLogSystem.Models.CsvUpload", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("device_id");

                    b.Property<DateTime?>("LogDate")
                        .HasColumnType("date")
                        .HasColumnName("log_date");

                    b.Property<string>("RawCsv")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("raw_csv");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("received_at_utc");

                    b.Property<int>("RowCount")
                        .HasColumnType("int")
                        .HasColumnName("row_count");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("source");

                    b.Property<bool>("Superseded")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("superseded");

                    b.Property<string>("TermId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("term_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("type");

                    b.Property<int>("UploadIndex")
                        .HasColumnType("int")
                        .HasColumnName("upload_index");

                    b.HasKey("Id")
                        .HasName("pk_csv_uploads");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_csv_uploads_device_id");

                    b.HasIndex("TermId", "Type")
                        .HasDatabaseName("ix_csv_uploads_term_id_type");

                    b.HasIndex("Type", "LogDate")
                        .HasDatabaseName("ix_csv_uploads_type_log_date");

                    b.ToTable("csv_uploads", (string)null);
                });

            modelBuilder.Entity("LeontecSyncLogSystem.Models.DeviceRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("FirstSeenUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("first_seen_utc");

                    b.Property<long>("FramesReceived")
                        .HasColumnType("bigint")
                        .HasColumnName("frames_received");

                    b.Property<long>("Heartbeats")
                        .HasColumnType("bigint")
                        .HasColumnName("heartbeats");

                    b.Property<DateTime?>("LastFrameUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_frame_utc");

                    b.Property<DateTime?>("LastHeartbeatUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_heartbeat_utc");

                    b.Property<DateTime?>("LastSeenUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_seen_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<long>("RecordsIngested")
                        .HasColumnType("bigint")
                        .HasColumnName("records_ingested");

                    b.Property<long>("Sessions")
                        .HasColumnType("bigint")
                        .HasColumnName("sessions");

                    b.Property<string>("WorkerId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("Address")
                        .IsUnique()
                        .HasDatabaseName("ix_devices_address");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("LeontecSyncLogSystem.Models.DirectEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Boxes")
                        .HasColumnType("int")
                        .HasColumnName("boxes");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("customer");

                    b.Property<int>("DeliveryQty")
                        .HasColumnType("int")
                        .HasColumnName("delivery_qty");

                    b.Property<string>("DeliveryTo")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("delivery_to");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("end_time");

                    b.Property<string>("FactoryCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("factory_code");

                    b.Property<string>("PartNo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("part_no");

                    b.Property<DateOnly?>("ShipDate")
                        .HasColumnType("date")
                        .HasColumnName("ship_date");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("start_time");

                    b.Property<long>("UploadId")
                        .HasColumnType("bigint")
                        .HasColumnName("upload_id");

                    b.Property<string>("YokooPartNo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("yokoo_part_no");

                    b.HasKey("Id")
                        .HasName("pk_direct_entries");

                    b.HasIndex("UploadId")
                        .HasDatabaseName("ix_direct_entries_upload_id");

                    b.ToTable("direct_entries", (string)null);
                });

            modelBuilder.Entity("LeontecSyncLogSystem.Models.MonitorEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Boxes")
                        .HasColumnType("int")
                        .HasColumnName("boxes");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("customer_code");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("end_time");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("item_code");

                    b.Property<int>("LoadedBoxes")
                        .HasColumnType("int")
                        .HasColumnName("loaded_boxes");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("SlipNo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("slip_no");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("status");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("status_code");

                    b.Property<long>("UploadId")
                        .HasColumnType("bigint")
                        .HasColumnName("upload_id");

                    b.HasKey("Id")
                        .HasName("pk_monitor_entries");

                    b.HasIndex("UploadId")
                        .HasDatabaseName("ix_monitor_entries_upload_id");

                    b.ToTable("monitor_entries", (string)null);
                });

            modelBuilder.Entity("LeontecSyncLogSystem.Models.PalletOp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("customer");

                    b.Property<string>("DeliveryRun")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("delivery_run");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("end_time");

                    b.Property<string>("ItemDetailRaw")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("item_detail_raw");

                    b.Property<string>("OpType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("op_type");

                    b.Property<string>("PlNo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("pl_no");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("start_time");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("status_code");

                    b.Property<long>("UploadId")
                        .HasColumnType("bigint")
                        .HasColumnName("upload_id");

                    b.HasKey("Id")
                        .HasName("pk_pallet_ops");

                    b.HasIndex("UploadId")
                        .HasDatabaseName("ix_pallet_ops_upload_id");

                    b.ToTable("pallet_ops", (string)null);
                });

            modelBuilder.Entity("LeontecSyncLogSystem.Models.PalletOpItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Boxes")
                        .HasColumnType("int")
                        .HasColumnName("boxes");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("item_code");

                    b.Property<long>("PalletOpId")
                        .HasColumnType("bigint")
                        .HasColumnName("pallet_op_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_pallet_op_items");

                    b.HasIndex("PalletOpId")
                        .HasDatabaseName("ix_pallet_op_items_pallet_op_id");

                    b.ToTable("pallet_op_items", (string)null);
                });

            modelBuilder.Entity("LeontecSyncLogSystem.Models.CsvUpload", b =>
                {
                    b.HasOne("LeontecSyncLogSystem.Models.DeviceRecord", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_csv_uploads_devices_device_id");
                });

            modelBuilder.Entity("LeontecSyncLogSystem.Models.DirectEntry", b =>
                {
                    b.HasOne("LeontecSyncLogSystem.Models.CsvUpload", null)
                        .WithMany()
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_direct_entries_csv_uploads_upload_id");
                });

            modelBuilder.Entity("LeontecSyncLogSystem.Models.MonitorEntry", b =>
                {
                    b.HasOne("LeontecSyncLogSystem.Models.CsvUpload", null)
                        .WithMany()
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_monitor_entries_csv_uploads_upload_id");
                });

            modelBuilder.Entity("LeontecSyncLogSystem.Models.PalletOp", b =>
                {
                    b.HasOne("LeontecSyncLogSystem.Models.CsvUpload", null)
                        .WithMany()
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pallet_ops_csv_uploads_upload_id");
                });

            modelBuilder.Entity("LeontecSyncLogSystem.Models.PalletOpItem", b =>
                {
                    b.HasOne("LeontecSyncLogSystem.Models.PalletOp", "PalletOp")
                        .WithMany("Items")
                        .HasForeignKey("PalletOpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pallet_op_items_pallet_ops_pallet_op_id");

                    b.Navigation("PalletOp");
                });

            modelBuilder.Entity("LeontecSyncLogSystem.Models.PalletOp", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
